openapi: '3.0.2'
info:
  title: myblogs 
  description: this is a blogs system for my first project
  version: '1.0'
servers:
  - url: https://localhost:8081
paths:
  /setup:
    get:
      tags:
        - Users
      description: '返回登陆界面'
      operationId: getSetUPView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/SetUpHtml"

    post:
      tags:
        - Users
      description: '接受用户注册信息,注册成功进入登录界面'
      operationId: login
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
                repassword:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Login"
  /login:
    get:
      tags:
        - Users
      description: '用户已有账户直接进入登陆界面'
      operationId: getLoginView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/LoginHtml"

    post:
      tags:
        - Users
      description: '接受用户登陆信息，信息匹配成功进入博客界面'
      operationId: blog
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Blog"            
    

  /blog:
    get:
      tags:
        - Blogs
      description: '点击博客界面编辑按钮，进入编辑界面'
      operationId: getBlogEditorView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/BlogEditorHtml"    
    

  /blogEditor:
   
    post:
      tags:
        - Blogs
      description: '用户编辑内容，添加至博客页面'
      operationId: blog
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Blog"

  

    
    
components:
  schemas:
    SetUpHtml:
      type: "string"
    SetUp:
      type: "object"
      properties:    
        view:
          type: "string" 
          
    
    LoginHtml:
      type: "string"
    Login:
      type: "object"
      properties:
        username:
          type: "string"
        view:
          type: "string"

    BlogHtml:
      type: "string"
    Blog:
      type: "object"
      properties:
        username:
          type: "string"
        view:
          type: "string"      

    BlogEditorHtml:
      type: "string"
    BlogEditor:
      type: "object"
      properties:
        username:
          type: "string"
        view:
          type: "string"     