openapi: '3.0.2'
info:
  title: myblogs 
  description: this is a blogs system for my first project
  version: '1.0'
servers:
  - url: http://localhost:8081
paths:
  
  /login:
    get:
      tags:
        - Users
      description: '返回登陆界面'
      operationId: getLoginView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/LoginHtml"

    post:
      tags:
        - Users
      description: '接受用户登陆信息，信息匹配成功进入博客界面'
      operationId: blog
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Blog"            
    
  /register:
    get:
      tags:
        - Users
      description: '没有用户点击注册按钮，进入登陆界面'
      operationId: getRegisterView
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/RegisterHtml"

    post:
      tags:
        - Users
      description: '接受用户注册信息,注册成功进入登录界面'
      operationId: login
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                password:
                  type: "string"
                repassword:
                  type: "string"
                view:
                  type: "string"
                  example: "(创建成功后)跳转至登陆界面"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Login"

  /blog:
    get:
      tags:
        - Blogs
      description: '返回博客界面'
      operationId: getBlogView
      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"
                properties:
                  username:
                    type: "string"
                  
                  
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/BlogHtml"    
    

  /edit:
   
    get:
      tags:
        - Blogs
      description: '点击博客界面编辑按钮，进入编辑界面'
      operationId: getEditView
     
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/EditHtml" 
    post:        
      tags:
        - Blogs
      description: '用户编辑内容，添加至博客页面'
      operationId: addBlog
      requestBody:
        required: true
        content:
          text/json: 
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                title:
                  type: "string"
                description:
                  type: "string"
                article:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/Blog"

  /delete:
    get:
      tags:
        - Blogs
      description: '删除blog所选信息，返回新的blog页面'
      operationId: deleteBlog
      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"
                properties:
                
                  blogId:
                    type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/BlogHtml"

  /update:
    get:
      tags:
        - Blogs
      description: '返回修改页面'
      operationId: updateBlog
      requestBody:
        required: true
        content:
          text/json:
            schema:
                type: "object"
                properties:                 
                  blogId:
                    type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/UpdateHtml"
    post:
      tags:
        - blogs
      description: '接受用户输入更新的信息,并返回blog页面'
      operationId: updateBlog
      requestBody:
        required: true
        content:
          text/json:
            schema:
              type: "object"
              properties:
                username:
                  type: "string"
                blogId:
                  type: "string"
                title:
                  type: "string"
                content:
                  type: "string"
      responses:
        '200':
          description: OK
          content:
            text/html:    
              schema:
                $ref: "#/components/schemas/BlogHtml"                


    
    
components:
  schemas:
    RegisterHtml:
      type: "string"
      example: "register.html" 
    Register:
      type: "object"
      properties:    
        view:
          type: "string" 
         
    
    LoginHtml:
      type: "string"
      example: "Login.html" 
    Login:
      type: "object"
      properties:
        username:
          type: "string"
        view:
          type: "string"

    BlogHtml:
      type: "object"        
      properties:
        username:
          type: "string"
        blogs:
          type: array
          items:
            $ref: "#/components/schemas/Blog"
        view:
          type: "string"
          example: "blog.html"   
    Blog:
      type: "object"
      properties:
        username:
          type: "string"              
        title:
          type: "string"        
        description:
          type: "string"  
        artcle:
          type: "string"
        view:
          type: "string"  
          example: "**个人博客"
             

    EditHtml:
      type: "string"
    Edit:
      type: "object"
      
       
 
